# Generated by Django 4.2.7 on 2026-05-26 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitors', '0002_vatican_task'),
        ('monitors', '0028_remove_monitortask_agent_target_and_more'),
    ]

    operations = [
    ]
