# Generated by Django 4.2.7 on 2026-06-05 10:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("monitors", "0028_remove_monitortask_agent_target_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="VaticanTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "booking_id",
                    models.CharField(
                        db_index=True,
                        help_text="Confirmation code from Google Sheets",
                        max_length=100,
                        unique=True,
                    ),
                ),
                ("target_date", models.DateField(help_text="Activity date")),
                (
                    "target_time",
                    models.CharField(help_text="Preferred time (HH:MM)", max_length=10),
                ),
                ("visitors", models.PositiveIntegerField(default=1)),
                (
                    "ticket_type",
                    models.IntegerField(
                        choices=[(0, "Standard Ticket"), (1, "Guided Tour")], default=0
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        blank=True,
                        help_text="Language code for guided tours (ENG, ITA, etc)",
                        max_length=10,
                        null=True,
                    ),
                ),
                ("customer_name", models.CharField(max_length=255)),
                ("customer_email", models.EmailField(max_length=254)),
                (
                    "customer_phone",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "participants_data",
                    models.JSONField(
                        blank=True,
                        help_text="Full participant details (JSON)",
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("checking", "AI Checking"),
                            ("awaiting_info", "Awaiting Info"),
                            ("ready", "Ready for Booking"),
                            ("booking", "Booking in Progress"),
                            ("booked", "Booked"),
                            ("verified", "Verified"),
                            ("tour_done", "Tour Done"),
                            ("review_sent", "Review Sent"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="new",
                        max_length=20,
                    ),
                ),
                (
                    "priority",
                    models.IntegerField(default=1, help_text="Higher = more urgent"),
                ),
                (
                    "missing_info",
                    models.TextField(
                        blank=True, help_text="AI-detected missing info", null=True
                    ),
                ),
                (
                    "contact_log",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Log of emails/messages sent",
                    ),
                ),
                ("last_checked", models.DateTimeField(blank=True, null=True)),
                (
                    "available_slots",
                    models.TextField(
                        blank=True,
                        help_text="Comma-separated available time slots",
                        null=True,
                    ),
                ),
                (
                    "booked_time",
                    models.CharField(
                        blank=True,
                        help_text="Actually booked time (HH:MM)",
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "checkout_url",
                    models.TextField(
                        blank=True, help_text="Epay checkout URL", null=True
                    ),
                ),
                (
                    "reference_code",
                    models.CharField(
                        blank=True,
                        help_text="Vatican reference/order number",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "verification_data",
                    models.JSONField(
                        blank=True, help_text="Result of ticket verification", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "vatican_tasks",
                "ordering": ["target_date", "-priority", "created_at"],
                "indexes": [
                    models.Index(fields=["booking_id"], name="vt_booking_id_idx"),
                    models.Index(fields=["status"], name="vt_status_idx"),
                    models.Index(fields=["target_date"], name="vt_target_date_idx"),
                ],
            },
        ),
    ]
