# Generated by Django 4.2.7 on 2026-06-19 09:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("monitors", "0029_merge_20260526_1407"),
        ("monitors", "0029_vaticantask"),
    ]

    operations = []
